import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"",ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",RESEND_API_KEY=Deno.env.get("RESEND_API_KEY")??"";
const ADMIN_EMAIL="patricia@calirh.com",MAX=8*1024*1024,BRAND_LOGO_URL="https://portal.calirh.com/assets/logo-cali-light.png";
function cors(req:Request){const o=req.headers.get("origin")??"";const ok=o==="https://portal.calirh.com"||o==="https://propostas.calirh.com"||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(o)||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(o);return{"Access-Control-Allow-Origin":ok?o:"https://portal.calirh.com","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json"}})}
function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]??c))}
function decode(value:unknown){const b=String(value??"").replace(/^data:application\/pdf;base64,/i,"").replace(/\s/g,"");if(!b||!/^[A-Za-z0-9+/]+={0,2}$/.test(b))throw new Error("PDF inválido.");const estimate=Math.floor(b.length*3/4);if(estimate>MAX)throw new Error("O PDF ultrapassa 8 MB.");const raw=atob(b),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(new TextDecoder().decode(bytes.slice(0,5))!=="%PDF-")throw new Error("O arquivo selecionado não é um PDF válido.");return{base64:b,bytes}}
function safeFile(v:unknown){return String(v??"proposta.pdf").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)}
function emailHtml(p:any,s:any,note:string){const first=esc(String(s.contact_name||"").split(/\s+/)[0]);return `<!doctype html><html><body bgcolor="#F7F3EE" style="margin:0;background:#F7F3EE;font-family:Arial,sans-serif;color:#2B2B2B"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:28px 14px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:auto;background:#fff;border:1px solid #EDE4DE;border-radius:14px;overflow:hidden"><tr><td bgcolor="#5A1E2D" style="padding:25px;text-align:center"><img src="${BRAND_LOGO_URL}" width="174" alt="CALI — HR for Business" style="display:block;width:174px;max-width:70%;height:auto;margin:0 auto;border:0"></td></tr><tr><td style="padding:34px 32px"><p style="font-size:16px;margin-top:0">Olá, ${first}.</p><p style="line-height:1.7">Concluí a proposta construída para a ${esc(s.company_name||"empresa")} a partir do contexto que você compartilhou comigo.</p>${note?`<p style="line-height:1.7">${esc(note)}</p>`:""}<p style="line-height:1.7">O PDF segue anexado para sua análise. Se fizer sentido, podemos conversar sobre o escopo, as prioridades e o melhor momento para começar.</p><table role="presentation" cellspacing="0" cellpadding="0" style="margin:26px 0"><tr><td bgcolor="#5A1E2D" style="border-radius:999px"><a href="https://wa.me/5541987791933" style="display:inline-block;padding:12px 22px;color:#fff;text-decoration:none;font-weight:bold;font-size:13px">Vamos conversar?</a></td></tr></table><p style="font-size:12px;color:#7A6F72;margin:30px 0 0">Patrícia Lima<br><span style="font-size:11px">People Advisory Executive · CALI</span></p></td></tr><tr><td bgcolor="#F7F3EE" style="padding:17px;text-align:center;font-size:10px;color:#8D8184">CALI · HR for Business · calirh.com · patricia@calirh.com</td></tr></table></td></tr></table></body></html>`}

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{error:"Método não permitido."},405);
 try{
  const auth=req.headers.get("authorization");if(!auth)return json(req,{error:"Sessão administrativa ausente."},401);
  const userClient=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const token=auth.replace(/^Bearer\s+/i,"");const{data:{user},error:userError}=await userClient.auth.getUser(token);if(userError||!user||String(user.email||"").toLowerCase()!==ADMIN_EMAIL)return json(req,{error:"Acesso não autorizado."},403);
  const body=await req.json(),proposalId=String(body.proposal_id||"");if(!/^[0-9a-f-]{36}$/i.test(proposalId))return json(req,{error:"Proposta inválida."},400);const pdf=decode(body.pdf_base64),note=String(body.note||"").trim().slice(0,1200);
  const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const{data:p,error:pError}=await admin.from("cali_proposals").select("*,submission:cali_submissions(*)").eq("id",proposalId).single();if(pError||!p?.submission)throw pError||new Error("Proposta não encontrada.");const s=p.submission;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s.contact_email))return json(req,{error:"O briefing não possui um e-mail válido."},400);
  const filename=safeFile(body.pdf_name||`Proposta-CALI-${s.company_name||s.contact_name}.pdf`),path=`${p.id}/v${p.version}-${Date.now()}-${filename}`;const{error:uploadError}=await admin.storage.from("cali-proposals").upload(path,pdf.bytes,{contentType:"application/pdf",upsert:false});if(uploadError)throw uploadError;
  if(!RESEND_API_KEY)throw new Error("RESEND_API_KEY não configurada.");const resend=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${RESEND_API_KEY}`,"Content-Type":"application/json","Idempotency-Key":`proposal-${p.id}-${new Date(p.updated_at).getTime()}`},body:JSON.stringify({from:"Patrícia Lima · CALI <patricia@calirh.com>",to:[s.contact_email],reply_to:ADMIN_EMAIL,subject:`Proposta ${s.company_name||s.contact_name} — CALI`,html:emailHtml(p,s,note),attachments:[{filename,content:pdf.base64}]})});const email=await resend.json().catch(()=>({}));if(!resend.ok)throw new Error(`Resend ${resend.status}: ${JSON.stringify(email)}`);
  const sentAt=new Date().toISOString();await Promise.all([admin.from("cali_proposals").update({status:"enviada",pdf_path:path,resend_email_id:email.id||null,sent_at:sentAt,updated_at:sentAt}).eq("id",p.id),admin.from("cali_submissions").update({status:"enviada",updated_at:sentAt}).eq("id",s.id),admin.from("cali_activity").insert({submission_id:s.id,proposal_id:p.id,event_type:"proposal_sent",metadata:{to:s.contact_email,email_id:email.id||null,pdf_path:path}})]);
  return json(req,{ok:true,email_id:email.id||null,to:s.contact_email});
 }catch(error){console.error(error);const message=error instanceof Error?error.message:"Falha no envio.";return json(req,{error:/PDF|8 MB|arquivo/i.test(message)?message:"Não foi possível enviar a proposta agora."},/PDF|8 MB|arquivo/i.test(message)?400:500)}
});
